### ISSUE TITLE
Bug in scalingFactor with custom base units

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#550]
The test below fails:

```
TEST(Units, customUnitsScalingFactorSimple)
{
    auto m = libcellml::Model::create("model");
    auto u1 = libcellml::Units::create("u1");
    m->addUnits(u1);
    auto u2 = libcellml::Units::create("u2");
    u2->addUnit("u1");
    m->addUnits(u2);

    m->linkUnits();

    EXPECT_TRUE(libcellml::Units::baseEquivalent(u1, u2)); // passes
    EXPECT_EQ(1.0, libcellml::Units::scalingFactor(u1, u2));  // fails, returns 0.0
    EXPECT_TRUE(libcellml::Units::equivalent(u1, u2)); // fails
}
```
... because of the the line below:
```
double Units::scalingFactor(const UnitsPtr &units1, const UnitsPtr &units2)
{
    if (!Units::baseEquivalent(units1, units2)) {
        return 0.0;
    }
    bool updateUnits1 = false;
    bool updateUnits2 = false;
    if ((units1 != nullptr) && (units2 != nullptr)) {
        if ((units1->unitCount() != 0) && (units2->unitCount() != 0)) { 
// <<<<< the unitCount for the base unit is 0, so this is skipped and the scaling factor is returned as 0
            double multiplier = 0.0;

            updateUnits1 = updateUnitMultiplier(multiplier, units2, 1, 0, 1);
            updateUnits2 = updateUnitMultiplier(multiplier, units1, 1, 0, -1);

            if (updateUnits1 && updateUnits2) {
                return std::pow(10, multiplier);
            }
        }
        if (units1->name() == units2->name()) {
            return 1.0;
        }
    }
    return 0.0; // <<<<< returns 0.0 when a base unit is compared
}
```

I'll include a fix for this at the same time as the other scalingFactor/dimensionality stuff.

**Comment by hsorby** [comment]
This has already been addressed in #547.

**Comment by kerimoyle** [comment]
> This has already been addressed in #547 

Alas, no, the test still fails.  It's not about the standard unit stuff, it's the custom units that are causing it.

**Comment by kerimoyle** [comment]
The fix for this is now in PR #554 in the interests of getting it in without depending on the `Issue` class existing.

**Comment by kerimoyle** [comment]
Closing this PR in favour of #554.
